config/routes.rb
Rails.application.routes.draw do
  
  # Root path
  root 'pages#index'

  # Searchs path
  resources :searches do
    collection do
      get :autocomplete
    end
  end
  get '/search/:id' => 'searches#link'
  match '/search/' => 'searches#search', :as => :searchable,via: [:get]

  # Professors
  resources :professors, path: :professores
  # Recomendations inside professors_path
  get '/recomendar/:id' => 'professors#recommended', as: :recommended
  get '/nao-recomendar/:id' => 'professors#unrecommended', as: :unrecommended

  # Users
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  # Admin system
  get '/admin' => "admin/admin#index",as: :admin 
  namespace :admin do
    resources :professors
    resources :users
  end

end

app/views/navbar/_user.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-user navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "InsProf", professors_path,:class => "navbar-brand"  %>
    </div>

    <%= form_tag  searchable_path, :class => "navbar-form navbar-left",:role => "search", method: :get do %>
    <div class="input-group">

      <%= text_field_tag :query, params[:query], class: "form-control ", id: "search" ,:name => "q",:placeholder => "Buscar" %>
      <div class="input-group-btn">
        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
      </div>
    </div>
    <% end %>


    <div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
    </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li class="dropdown">
          <a href="#" data-toggle="dropdown" class="dropdown-toggle"><%= current_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% if current_user.admin %>
              <li><%= link_to "Admin", admin_path %></li>
            <% end %>
            <li><%= link_to current_user.email, edit_user_registration_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
        <% if Professor.where(:user_id => current_user.id).first.present? %>
          <li class="active"><%= link_to "Editar professor",edit_professor_path(current_user.professor) %></li>
        <% else %>
        <li class="active"><%= link_to "Registre-se como professor",new_professor_path %></li>
        <% end %>
        <% else %>
        <li class="active"><%= link_to "Registre-se como professor",new_professor_path %></li>
     <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>