config/routes.rb
Rails.application.routes.draw do
  
  # Root path
  root 'pages#index'

  # Searchs path
  resources :searches do
    collection do
      get :autocomplete
    end
  end
  get '/search/:id' => 'searches#link'
  match '/search/' => 'searches#search', :as => :searchable,via: [:get]

  # Professors
  resources :professors, path: :professores
  # Recomendations inside professors_path
  get '/recomendar/:id' => 'professors#recommended', as: :recommended
  get '/nao-recomendar/:id' => 'professors#unrecommended', as: :unrecommended

  # Users
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  # Admin system
  get '/admin' => "admin/admin#index",as: :admin 
  namespace :admin do
    resources :professors
    resources :users
  end

end

app/models/user.rb
require 'open-uri'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable,
  :omniauthable, :omniauth_providers => [:facebook]

  # Relations
  has_one :professor
  
  # Validations
  validates :name, presence: true, length: { maximum: 100 }

  # Gem socialization
  acts_as_liker # Can be liked(recommend) other user
  acts_as_follower # Tricker for not recommended


  # Facebook Autentification for user, this function set fields to save on database via social login check gem 'omniauth-facebook'
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def update_with_password(params={}) 
    if params[:password].blank? 
      params.delete(:password) 
      params.delete(:password_confirmation) if params[:password_confirmation].blank? 
    end 
    update_attributes(params) 
  end

  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
	respond_to :html

	def index
		@users = User.all.order("created_at desc").page(params[:page]).per(20)
		respond_with(@users)
	end

end

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Entrar", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Criar conta", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu sua senha ?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Não recebeu as informações de confirmação ?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>