config/routes.rb
Rails.application.routes.draw do
  
  # Root path
  root 'pages#index'

  # Searchs path
  resources :searches do
    collection do
      get :autocomplete
    end
  end
  get '/search/:id' => 'searches#link'
  match '/search/' => 'searches#search', :as => :searchable,via: [:get]

  # Professors
  resources :professors, path: :professores
  # Recomendations inside professors_path
  get '/recomendar/:id' => 'professors#recommended', as: :recommended
  get '/nao-recomendar/:id' => 'professors#unrecommended', as: :unrecommended

  # Users
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  # Admin system
  get '/admin' => "admin/admin#index",as: :admin 
  namespace :admin do
    resources :professors
    resources :users
  end

end

app/models/professor.rb
class Professor < ActiveRecord::Base

  # After and before validations
  include Searchable


  # Relations
  belongs_to :user

  has_many :courses, :dependent => :destroy
  accepts_nested_attributes_for :courses, :reject_if => :all_blank, :allow_destroy => true

  # Validations
  validates :email, presence: true
  validates :price, presence: true
  validates :semester, presence: true
  validates :major, presence: true
  validates :horario, presence: true
  validates :name, presence: true

  # PaperClip + ftp
  has_attached_file :image,:styles => {
    :large => "512x512" ,
    :medium => "200x200" ,
    :small => "168x168",
    :thumb => "40x40",
    :tiny => "32x32"
    },
    :url  => "/images/professor/:id-:basename.:style.:extension",
    :path => ":rails_root/public/images/professor/:id-:basename.:style.:extension",
    :default_url => :set_default_url

    validates :image, :attachment_presence => true
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
    validates_attachment_size :image, :less_than => 10.megabytes

  # if user dont have image
  def set_default_url
    "/img/missing.png"
  end
  # End --- 

  # Gem socialization
  acts_as_likeable # Can be recomended
  acts_as_followable # Tricker for not recommended


  # FriendlyID Gem
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [:name,
      [:name, :id]
    ]
  end
  # end


end

app/controllers/admin/professors_controller.rb
class Admin::ProfessorsController < Admin::AdminController
	before_action :set_professor, only: [:edit, :update, :destroy]
	respond_to :html

	def index
		@professors = Professor.all.order("created_at desc").page(params[:page]).per(20)
		respond_with(@professors)
	end
	
	private

	def set_professor
		@professor = Professor.find(params[:id])
	end
	
	def professor_params
		params.require(:professor).permit(:name,:user_id, :email, :price, :nota_pi, :nota_pf, :cr, :ranking, :horario, :image, :major, :semester,:description, courses_attributes: [:id, :name,:nota_pf,:nota_pi, :done, :_destroy])
	end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy,:recommended, :unrecommended]
  before_action :check_user_professor, only: [:new, :create]
  before_action :check_security, only: [:edit, :update, :destroy, :create]
  before_action :check_user_liker, only: [:recommended, :unrecommended]


  respond_to :html

  def index
    @professors = Professor.all.order("created_at desc").page(params[:page]).per(70)
    respond_with(@professors)
  end

  def show
    respond_with(@professor)
  end

  def new
    @professor = Professor.new
    respond_with(@professor)
  end

  def edit
  end

  def create
    @professor = Professor.new(professor_params)
    @professor.user_id = current_user.id
    @professor.save
    respond_with(@professor)
  end

  def update
    @professor.update(professor_params)
    respond_with(@professor)
  end

  def destroy
    @professor.destroy
    respond_with(@professor)
  end

  def unrecommended
    current_user.toggle_follow!(@professor)
    @professor.unrecommended_count = @professor.followers(User).count
    @professor.save!
    respond_to do |format|               
      format.js
    end
  end

  def recommended
    current_user.toggle_like!(@professor)
    @professor.recommended_count = @professor.likers(User).count
    @professor.save!
    respond_to do |format|               
      format.js
    end
  end

  private
  def set_professor
    @professor = Professor.friendly.find(params[:id])
  end
  
  def check_user_professor
    if current_user 
      @user_has_professor = Professor.where(:user_id => current_user.id).first
      if @user_has_professor.present?
        redirect_to professors_path, notice: "Você já é cadastrado como professor"
      end
    else
      redirect_to  new_user_session_path, notice: "Você precisa estar logado"
    end
  end

  def check_user_liker
    unless current_user
      redirect_to  new_user_session_path, notice: "Você precisa estar logado"
    end
  end

  def check_security
    if @user_has_professor = Professor.where(:user_id => current_user.id).first.id != current_user.id && current_user.admin == false || current_user.present? == false
      redirect_to root_path, notice: "Você não é o dono do cadastro !!"
    end
  end

  def professor_params
    params.require(:professor).permit(:name,:user_id, :email, :price, :nota_pi, :nota_pf, :cr, :ranking, :horario, :image, :major, :semester,:description, courses_attributes: [:id, :name,:nota_pf,:nota_pi, :done, :_destroy])
  end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_course_fields.html.erb
<div class="nested-fields">
	<div class="field">
		<div class="row">
			<div class="col-sm-3">
				<%= f.text_field :name %>
			</div>
			<div class="col-sm-3">
				<%= f.number_field :nota_pi, step: 'any' %>
			</div>
			<div class="col-sm-3">
				<%= f.number_field :nota_pf, step: 'any'  %>
			</div>
			<div class="col-sm-1">
				<%= link_to_remove_association icon('minus-circle'), f ,:class => "btn btn-danger buttom-nested" %>
			</div>
		</div>
	</div>
</div>

app/views/professors/_form.html.erb
<%= bootstrap_form_for(@professor) do |f| %>
<div class="field">
  <%= f.text_field :name,:autofocus => true %>
</div>

<div class="field">
  <%= f.text_field :email %>
</div>

<%= f.file_field :image %>
<div class="row">
  <div class="col-sm-4">
    <div class="form-group">
      <% if @professor.image.present? %>
      <%= image_tag @professor.image.url(:medium),:class => "img-responsive img-profile-preload hide-change" %>
      <% end %>
      <img id="image-box" src="#" alt="" class="img-responsive img-profile-preload" />
    </div>
  </div>
</div>

<legend>Matérias que você da aula</legend>

<div id="courses">
  <%= f.fields_for :courses do |course| %>
  <%= render 'course_fields', :f => course %>
  <% end %>
  <div class="form-group">
    <%= link_to_add_association 'Adicionar matéria', f, :courses, :class => "btn btn-success" %>
  </div>
</div>
<hr>

<div class="field">
  <%= f.select :major, options_for_select(["Administração", "Economia"],@professor.major), { prompt: "Selecione...."} %>   
</div>

<div class="field">
  <%= f.select :semester, options_for_select([ 1,2,3,4,5,6,7,8],@professor.semester), { prompt: "Selecione...."} %>   
</div>

<div class="field">
  <%= f.text_field :price %>
</div>

<div class="field">
  <%= f.text_area :horario %>
</div>

<div class="field">
  <%= f.text_area :description %>
</div>

<div class="actions">
  <%= f.submit "Salvar", :class => "btn btn-success btn-lg pull-right" %>
</div>
<% end %>
<script>
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        $('#image-box').attr('src', e.target.result);
        $('.hide-change').hide();
      }
      reader.readAsDataURL(input.files[0]);
    }
  }
  $("#professor_image").change(function(){
    readURL(this);
  });
</script>

app/views/professors/_recommended.html.erb
<div class="col-sm-6 col-xs-2">
	<center>
		<h4>
			<%= @professor.recommended_count.to_i %>
			<% if current_user %>
				<% if @professor.liked_by?(current_user) %>
				<%= link_to "<i class='fa fa-thumbs-o-up'></i>".html_safe,recommended_path(@professor),:remote => true %>
					<% else %>
				<%= link_to "<i class='fa fa-thumbs-o-up'></i>".html_safe,recommended_path(@professor),:remote => true %>
				<% end %>
			<% else %>
				<%= link_to "<i class='fa fa-thumbs-o-up'></i>".html_safe, new_user_session_path %>
			<% end %>
		</h4>
	</center>
</div>

app/views/professors/_unrecommended.html.erb
<div class="col-sm-6 col-xs-2">
	<center>
		<h4>
			<%= @professor.unrecommended_count.to_i %>
			<% if current_user %>
				<% if @professor.followed_by?(current_user) %>
				<%= link_to "<i class='fa fa-thumbs-o-down'></i>".html_safe,unrecommended_path(@professor),:remote => true %>
				<% else %>
				<%= link_to "<i class='fa fa-thumbs-o-down'></i>".html_safe,unrecommended_path(@professor),:remote => true %>
				<% end %>
				<% else %>
				<%= link_to "<i class='fa fa-thumbs-o-down'></i>".html_safe, new_user_session_path %>
			<% end %>
		</h4>
	</center>
</div>

app/views/professors/edit.html.erb
<%= render 'navbar/user' %>
<div class="container">
	<div class="container-box">
		<div class="row">
			<div class="col-sm-12">
				<h4>Editar meu cadastro como professor</h4>
				<%= render 'form' %>
				<%= link_to 'Cancelar meu cadastro como professor', @professor, method: :delete, data: { confirm: 'Tem certeza ???!' },:class => "pull-left btn btn-danger" %>
			</div>
		</div>
	</div>
</div>

app/views/professors/index.html.erb
<%= content_for :title, "InsProf | Professores" %>
<%= render 'navbar/user' %>
<div id="container">
  <div class="container">
    <p id="notice"><%= notice %></p>
    <% @professors.each do |professor| %>  
    <div class="item">
      <div class="panel panel-default">
        <%= link_to (image_tag professor.image.url(:medium)),professor %>
        <div class="panel-body">
          <%= link_to professor.user.name,professor %>
          <div class="pull-right">
            <div class="text text-muted" >
              <small><%= "#{icon('thumbs-up')} #{professor.recommended_count}".html_safe  %></small>
              <small><%= "#{icon('thumbs-down')} #{professor.unrecommended_count}".html_safe  %></small>
            </div>
          </div>
          <h5><%= professor.price %></h5>
          <hr>
          <div class="courses">
            <div class="text-center text-muted courses-more">
             <small> Ver mais </small>
             <hr>
            </div>
            <table class="table table table-hover">
              <thead>
                <tr>
                  <th><small>Curso</small></th>
                  <th><small>PI</small></th>
                  <th><small>PF</small></th>
                </tr>
              </thead>
              <tbody>
                <% professor.courses.each do |course| %>
                  <tr>
                    <td><small><%= course.name %></small></td>
                    <td><small><%= course.nota_pi %></small></td>
                    <td><small><%= course.nota_pf %></small></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>
<center>
  <%= paginate @professors,:left => 1, :right => 3,:theme => 'twitter-bootstrap-3' %>
</center>

<script type="text/javascript">
  $(document).ready(function(){
    $("#container").gridalicious({
      animate: true,
      width: 200,
      height: 300
    })
  });
</script>
<script>
  $('.courses').hover(
    function () {
      $(this).animate({
        height: '200px',
        width: '150px'
      }, 1);
    },

    function () {
      $(this).animate({
        height: '15px',
        width: '150px'
      }, 1);
    });
</script>

app/views/professors/new.html.erb
<%= render 'navbar/user' %>
<div class="container">
	<div class="container-box">
		<div class="row">
			<div class="col-sm-12">
				<h4>Cadastre-se como professor</h4>
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/professors/recommended.js.erb
$("#recommended-hide").hide();
$("#recommended").html("<%= escape_javascript(render('professors/recommended')) %>")

app/views/professors/show.html.erb
<%= content_for :title, "InsProf | #{@professor.name}" %>
<%= render 'navbar/user' %>
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class="container-box">
        <p id="notice"><%= notice %></p>
        <div class="row">
          <div class="col-sm-2">
            <%= image_tag @professor.image.url(:medium),:class => "img-rounded img-responsive" %>
            <div class="row"> 
              <div id="recommended-hide">
                <%= render 'professors/recommended' %>
              </div>
              <div id="recommended"></div>
              <div id="unrecommended-hide">
                <%= render 'professors/unrecommended' %>
              </div>
              <div id="unrecommended"></div>
            </div>
            <%= render_shareable :buttons=> ['facebook'], :url=> request.original_url, :facebook=> {:send=> true,:share => true, :url=> request.original_url, :action => 'recommend'} %>
          </div>
          <div class="col-sm-5">
            <div class="form-group">
              <h4><%= @professor.user.name %></h4>
              <%= @professor.email %>
            </div>
            <%= link_to "Entrar em contato pelo facebook","http://www.facebook.com/#{@professor.user.uid}",:target => "_blank" if @professor.user.uid.present? %>
            <hr>
            <p>
              <strong>Preço:</strong>
              <%= @professor.price %>
            </p>
            <p>
              <strong>Horário:</strong>
              <%= simple_format @professor.horario %>
            </p>
            <% if @professor.description.present? %>
            <p>
              <strong>O que faz dele um bom professor:</strong>
              <%= simple_format @professor.description %>
            </p>
            <% end %>
          </div>
          <div class="col-sm-5">
            <h4>Matérias</h4>
            <table class="table table table-hover">
              <thead>
                <tr>
                  <th>Curso</th>
                  <th>PI</th>
                  <th>PF</th>
                </tr>
              </thead>
              <tbody>
               <% @professor.courses.each do |course| %>
               <tr>
                <td><%= course.name %></td>
                <td><%= course.nota_pi %></td>
                <td><%= course.nota_pf %></td>
              </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> 

app/views/professors/unrecommended.js.erb
$("#unrecommended-hide").hide();
$("#unrecommended").html("<%= escape_javascript(render('professors/unrecommended')) %>")