config/routes.rb
Rails.application.routes.draw do
  
  # Root path
  root 'pages#index'

  # Searchs path
  resources :searches do
    collection do
      get :autocomplete
    end
  end
  get '/search/:id' => 'searches#link'
  match '/search/' => 'searches#search', :as => :searchable,via: [:get]

  # Professors
  resources :professors, path: :professores
  # Recomendations inside professors_path
  get '/recomendar/:id' => 'professors#recommended', as: :recommended
  get '/nao-recomendar/:id' => 'professors#unrecommended', as: :unrecommended

  # Users
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  # Admin system
  get '/admin' => "admin/admin#index",as: :admin 
  namespace :admin do
    resources :professors
    resources :users
  end

end

app/models/search.rb
class Search < ActiveRecord::Base
	#Search
	searchkick autocomplete: ['name']

	def search_data
		as_json only: [:name, :id]
    	{
    		name: name,
    		id: id
    	}
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:link]

  respond_to :html

  def autocomplete
    render json: Search.search(params[:query], autocomplete: true, limit: 10, fields: [:name, :id]).map{|search| search.slice(:name, :id) }
  end


  def search
    @search = Search.search(params[:q], limit: 40,fields: [:name])
  end


  private
    def set_search
      @search = Search.find(params[:id])
    end

    def search_params
      params.require(:search).permit(:name, :search_id, :search_model)
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :search_id %><br>
    <%= f.number_field :search_id %>
  </div>
  <div class="field">
    <%= f.label :search_model %><br>
    <%= f.text_field :search_model %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Searches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Search</th>
      <th>Search model</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.name %></td>
        <td><%= search.search_id %></td>
        <td><%= search.search_model %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New Search</h1>

<%= render 'form' %>

<%= link_to 'Back', searches_path %>

app/views/searches/search.html.erb
<%= render 'navbar/user' %>
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<div class="container-box">
			<% if @search.count > 0 %>
				Encontrados <%= @search.count %> resultados
			<% else %>
				Sem resultados para a pesquisa =(
			<% end %>
			<hr>

			<table class="table table table-hover">
				<thead>
              		<tr>
              			<th></th>
		                <th><small>Professor</small></th>
		                <th><small>Matéria</small></th>
		                <th><small>PI</small></th>
		                <th><small>PF</small></th>
              		</tr>
            	</thead>
				 <tbody>
				<% @search.each do |result| %>
				<tr>
					<% if result.search_model == "Course" %>
						<% @course = Course.find(result.search_id) %>
						<td><%= link_to (image_tag @course.professor.image.url(:thumb)),professor_path(@course.professor) %></td>
						<td><%= link_to @course.professor.name,professor_path(@course.professor) %></td>
						<td><%= @course.name %></td>
						<td><%= @course.nota_pi %></td>
						<td><%= @course.nota_pf %></td>
					<% else %> 
						<% @professor = Professor.find(result.search_id) %>
						<td><%= link_to (image_tag @professor.image.url(:thumb)),professor_path(@professor) %></td>
						<td><%= link_to @professor.name,professor_path(@professor) %></td>
						<td></td>
						<td></td>
						<td></td>
					<% end %>
				</tr>
				<% end %>
			</table>
			</div>
		</div>
	</div>
</div>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @search.name %>
</p>

<p>
  <strong>Search:</strong>
  <%= @search.search_id %>
</p>

<p>
  <strong>Search model:</strong>
  <%= @search.search_model %>
</p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>